### ISSUE TITLE
Worker nodes not able to delete message from azure storage queue.

### ISSUE THREAD

**Issue by danishk6100** [bidossessi/dramatiq-azure#27]
I am trying dramatiq-azure with the following code:

@dramatiq.actor(queue_name="default", store_results=True)
def count_words(url):
    response = requests.get(url)
    count = len(response.text.split(" "))
    print(f"There are {count} words at {url!r}.")
    return count

@app.route("/")
def hello_world():
    urls = [
        "https://google.com",
        "https://facebook.com",
        "https://rabbitmq.com",
        "https://bmw.com",
        "https://apple.com",
        "https://amazon.com"
    ]
    x = [count_words.send(url) for url in urls]
    return "Successfully sent all the messages"

But the workers are throwing this error:

There are 481 words at 'https://google.com'.
[2023-07-18 18:01:50,882] [PID 15824] [Thread-3] [dramatiq.worker.ConsumerThread(default)] [ERROR] Unhandled error during post_process_message(count_words('https://rabbitmq.com')).  You've found a bug in Dramatiq.  Please report it!
Although your message has been processed, it will be processed again once this worker is restarted.
Traceback (most recent call last):
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\dramatiq\worker.py", line 352, in post_process_message
    self.consumer.ack(message)
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\dramatiq_azure\asq.py", line 112, in ack
    self.__remove_from_queue(message)
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\dramatiq_azure\asq.py", line 107, in __remove_from_queue
    self.q_client.delete_message(message._asq_message)
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\azure\storage\queue\_queue_client.py", line 956, in delete_message
    process_storage_error(error)
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\azure\storage\queue\_shared\response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\azure\storage\queue\_queue_client.py", line 949, in delete_message
    self._client.message_id.delete(
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\azure\core\tracing\decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\azure\storage\queue\_generated\operations\_message_id_operations.py", line 279, in delete
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Users\danish.kapoor\Desktop\Flask APP\myproject\env\Lib\site-packages\azure\core\exceptions.py", line 112, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified message does not exist.
RequestId:351e1b3c-7003-006b-4773-b938f3000000
Time:2023-07-18T12:31:50.5462703Z
ErrorCode:MessageNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>MessageNotFound</Code><Message>The specified message does not exist.
RequestId:351e1b3c-7003-006b-4773-b938f3000000
Time:2023-07-18T12:31:50.5462703Z</Message></Error>

Any suggestions what needs to be changed?

**Comment by danishk6100** [comment]
could you please provide any update on this issue. We need this urgently.

**Comment by bidossessi** [comment]
Can you create a ASQ-only test case that reproduces the issue? There are too many external factors here (i.e. flask, network calls).

**Comment by dvazar** [comment]
@bidossessi We have also encountered this problem. In our case, it is reproduced every time when the message processing by the actor exceeds the set timeout of message visibility in the queue.

For example, the message visibility timeout is 10 minutes.
1. The actor "A_1" starts processing message "M". And does so for e.g. 15 minutes.
2. After 10 minutes, message "M" becomes visible in the queue again and another actor "A_2" starts processing it. At this stage we have two actors processing the same message "M".
3. Now one of the actors finishes processing message "M" and removes this message from the queue.
4. The other actor also finishes processing the message "M" and gives the command to delete the message. This is where the error occurs. Azure says that no message was found and Dramatiq logs "You've found a bug in Dramatiq". After that the worker hangs, it just stops processing the next messages.

Hopes it make sense.

**Comment by bidossessi** [comment]
Is the expected behaviour that the worker does not hang? This might probably better be handled in the worker code?

The following bugs might be relevant:

- https://github.com/Bogdanp/dramatiq/issues/445
- https://github.com/Bogdanp/dramatiq/issues/211

**Comment by bidossessi** [comment]
I just  merged #125 with two new test cases.
Feel free to reopen this ticket if your issue is still not resolved.
